version: '3'
services:
  postgres:
    image: "postgres:14.4-alpine"
    ports:
      - "8866:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "bank"
